import { StyleSheet, Dimensions } from "react-native";
const { height, width } = Dimensions.get('window');

export const deviceDetailModalStyles = StyleSheet.create({
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    backdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContent: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      maxHeight: height * 0.10,
      minHeight: height * 0.8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 20,
    },
    handleBar: {
      width: 40,
      height: 4,
      backgroundColor: '#D1D5DB',
      borderRadius: 2,
      alignSelf: 'center',
      marginTop: 12,
      marginBottom: 8,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#F3F4F6',
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    headerText: {
      marginLeft: 16,
      flex: 1,
    },
    powerIcon: {
      width: 52,
      height: 52,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    powerIconOn: {
      backgroundColor: '#DCFCE7',
    },
    powerIconOff: {
      backgroundColor: '#F9FAFB',
    },
    powerIconText: {
      fontSize: 24,
    },
    deviceName: {
      fontSize: 24,
      fontWeight: '800',
      color: '#111827',
      marginBottom: 2,
    },
    deviceType: {
      fontSize: 16,
      color: '#6B7280',
      fontWeight: '500',
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F9FAFB',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    closeButtonText: {
      fontSize: 18,
      color: '#6B7280',
      fontWeight: '600',
    },
    modalBody: {
      flex: 1,
      paddingHorizontal: 24,
    },
    statusCard: {
      marginTop: 20,
      marginBottom: 24,
      borderRadius: 20,
      overflow: 'hidden',
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    statusGradient: {
      padding: 24,
    },
    statusContent: {
      flex: 1,
    },
    statusLabel: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      fontWeight: '500',
      marginBottom: 4,
    },
    statusValue: {
      fontSize: 28,
      fontWeight: '800',
      color: '#FFFFFF',
      marginBottom: 8,
    },
    statusTime: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.7)',
      fontWeight: '400',
    },
    statusIndicator: {
      position: 'absolute',
      top: 20,
      right: 20,
    },
    statusDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    statusDotActive: {
      backgroundColor: '#FFFFFF',
      shadowColor: '#FFFFFF',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.8,
      shadowRadius: 4,
    },
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 24,
    },
    metricCard: {
      flex: 1,
      minWidth: (width - 60) / 2,
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8F5E8',
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    metricIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    metricIcon: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    metricTitle: {
      fontSize: 14,
      color: '#6B7280',
      fontWeight: '500',
      marginBottom: 8,
    },
    metricValueContainer: {
      flexDirection: 'row',
      alignItems: 'baseline',
    },
    metricValue: {
      fontSize: 24,
      fontWeight: '800',
      color: '#111827',
    },
    metricUnit: {
      fontSize: 16,
      color: '#9CA3AF',
      fontWeight: '500',
      marginLeft: 4,
    },
    quickStats: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#111827',
      marginBottom: 16,
    },
    statsContainer: {
      flexDirection: 'row',
      backgroundColor: '#F0FDF4',
      padding: 20,
      borderRadius: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E8F5E8',
    },
    statItem: {
      flex: 1,
      alignItems: 'center',
    },
    statValue: {
      fontSize: 24,
      fontWeight: '800',
      color: '#111827',
      marginBottom: 4,
    },
    statLabel: {
      fontSize: 12,
      color: '#6B7280',
      fontWeight: '500',
      textAlign: 'center',
    },
    statDivider: {
      width: 1,
      height: 40,
      backgroundColor: '#D1FAE5',
      marginHorizontal: 16,
    },
    modalFooter: {
      padding: 24,
      borderTopWidth: 1,
      borderTopColor: '#E8F5E8',
      backgroundColor: '#F9FDF9',
    },
    toggleButton: {
      borderRadius: 16,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    toggleOn: {
      // Styles handled by gradient
    },
    toggleOff: {
      // Styles handled by gradient
    },
    toggleButtonGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 18,
      paddingHorizontal: 24,
    },
    buttonIcon: {
      width: 24,
      height: 24,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    toggleButtonIconText: {
      fontSize: 18,
      color: '#FFFFFF',
    },
    toggleButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });