import { StyleSheet } from "react-native";
export const welcomeStyles = StyleSheet.create({
    container: {
      marginHorizontal: 16,
      marginTop: 20,
      marginBottom: 16,
    },
    card: {
      borderRadius: 0,
      padding: 20,
      // borderWidth: 1,
      borderColor: 'rgba(229, 231, 235, 0.3)',
      // shadowColor: '#10B981',
      // shadowOffset: {
      //   width: 0,
      //   height: 8,
      // },
      // shadowOpacity: 0.12,
      // shadowRadius: 16,
      elevation: 0,
      overflow: 'hidden',
      position: 'relative',
    },
    content: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    textSection: {
      flex: 1,
    },
    greeting: {
      fontSize: 14,
      color: '#6B7280',
      fontWeight: '500',
      marginBottom: 4,
    },
    name: {
      fontSize: 20,
      fontWeight: '800',
      color: '#1F2937',
      marginBottom: 6,
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: 14,
      color: '#059669',
      fontWeight: '600',
    },
    profileSection: {
      alignItems: 'center',
    },
    profileContainer: {
      position: 'relative',
    },
    profileBackground: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      //shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    statusIndicator: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: '#22C55E',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    decorativeCircle1: {
      position: 'absolute',
      width: 70,
      height: 70,
      borderRadius: 40,
      backgroundColor: 'rgba(16, 185, 129, 0.05)',
      top: -20,
      right: -10,
    },
    decorativeCircle2: {
      position: 'absolute',
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: 'rgba(34, 197, 94, 0.04)',
      bottom: -15,
      left: -15,
    },
  });