import { Dimensions, StyleSheet } from 'react-native';
const { height } = Dimensions.get("window");
export const settingsStyles = StyleSheet.create({
    container: {
        flex: 1,
      },
      background: {
        flex: 1,
      },
      safeArea: {
        flex: 1,
      },
      scrollView: {
        flex: 1,
      },
      scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 100, // Extra padding for floating tab bar
      },
      backgroundCircles: {
        position: 'absolute',
        width: '100%',
        height: '100%',
      },
      circle: {
        position: 'absolute',
        borderRadius: 1000,
      },
      circle1: {
        width: 200,
        height: 200,
        top: -100,
        right: -100,
        backgroundColor: 'rgba(0, 201, 87, 0.08)',
      },
      circle2: {
        width: 150,
        height: 150,
        bottom: -75,
        left: -75,
        backgroundColor: 'rgba(16, 185, 129, 0.06)',
      },
      circle3: {
        width: 100,
        height: 100,
        top: height * 0.3,
        left: -50,
        backgroundColor: 'rgba(34, 197, 94, 0.05)',
      },
      alertBanner: {
        backgroundColor: '#ef4444',
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      headerContainer: {
        paddingTop: 20,
        paddingBottom: 8,
        backgroundColor: 'transparent',
        zIndex: 2,
      },
      header: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: 0,
        letterSpacing: 0,
      },
      subtitle: {
        fontSize: 15,
        color: '#6B7280',
        fontWeight: '500',
      },
      alertContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
      },
      alertText: {
        marginLeft: 12,
        flex: 1,
      },
      alertMessage: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
      },
      alertTimestamp: {
        color: '#fff',
        fontSize: 12,
        opacity: 0.8,
        marginTop: 2,
      },
      dismissButton: {
        padding: 4,
      },
      // Redesigned User Card Styles
      userCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#f0f0f0',
      },
      profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
      },
      profileImageContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#f0fdf4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
        borderWidth: 2,
        borderColor: '#dcfce7',
      },
      profileInfo: {
        flex: 1,
      },
      userName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 2,
      },
      userRole: {
        fontSize: 14,
        color: '#059669',
        fontWeight: '500',
      },
      userDetails: {
        gap: 16,
      },
      detailRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
      },
      detailIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#f0fdf4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      detailContent: {
        flex: 1,
      },
      detailLabel: {
        fontSize: 12,
        color: '#6b7280',
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
      },
      detailValue: {
        fontSize: 14,
        color: '#1f2937',
        fontWeight: '500',
      },
      phoneEditContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
      },
      phoneInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
        marginRight: 8,
      },
      saveButton: {
        backgroundColor: '#059669',
        borderRadius: 6,
        padding: 8,
      },
      phoneContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
      },
      editButton: {
        marginLeft: 8,
        padding: 4,
      },
      // Regular card styles (with elevation removed from user card)
      card: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
      },
      collapsibleHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1f2937',
        marginLeft: 8,
      },
      deviceContent: {
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        paddingTop: 16,
      },
      deviceList: {
        gap: 12,
      },
      deviceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#f9fafb',
        borderRadius: 8,
      },
      deviceInfo: {
        flex: 1,
      },
      deviceName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
      },
      deviceStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
      },
      statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
      },
      statusText: {
        fontSize: 12,
        color: '#6b7280',
      },
      removeButton: {
        padding: 8,
      },
      addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#059669',
        borderRadius: 8,
        padding: 16,
        marginTop: 12,
      },
      addButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
      },
      thresholdSettings: {
        gap: 16,
      },
      settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      settingLabel: {
        fontSize: 14,
        color: '#1f2937',
        fontWeight: '500',
        flex: 1,
      },
      settingInput: {
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
        width: 80,
        textAlign: 'center',
      },
      resetButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderWidth: 1,
        borderColor: '#059669',
        borderRadius: 8,
        marginTop: 8,
      },
      resetButtonText: {
        color: '#059669',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
      },
      emergencyCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 2,
        borderColor: '#fef2f2',
      },
      emergencyTitle: {
        color: '#ef4444',
      },
      emergencyWarning: {
        fontSize: 14,
        color: '#ef4444',
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 16,
        padding: 12,
        backgroundColor: '#fef2f2',
        borderRadius: 6,
      },
      emergencyControls: {
        gap: 16,
      },
      masterToggleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: '#f9fafb',
        borderRadius: 8,
      },
      toggleInfo: {
        flex: 1,
      },
      toggleLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
      },
      toggleDescription: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
      },
      emergencyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ef4444',
        borderRadius: 8,
        padding: 16,
      },
      resetSystemButton: {
        backgroundColor: '#dc2626',
      },
      emergencyButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
      },
      logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        // backgroundColor: '#059669',
        // borderRadius: 8,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 32,
        marginTop: 5,
      },
      logoutButtonText: {
        color: '#000',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
      },
});