import { StyleSheet } from "react-native";
export const alertSetupStyles = StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    keyboardView: {
      flex: 1,
    },
    backgroundCircles: {
      position: 'absolute',
      width: '100%',
      height: '100%',
    },
    circle: {
      position: 'absolute',
      borderRadius: 1000,
    },
    circle1: {
      width: 250,
      height: 250,
      top: -125,
      right: -125,
      backgroundColor: 'rgba(16, 185, 129, 0.06)',
    },
    circle2: {
      width: 180,
      height: 180,
      bottom: -90,
      left: -90,
      backgroundColor: 'rgba(34, 197, 94, 0.05)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 20,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      flex: 1,
      textAlign: 'center',
    },
    stepIndicator: {
      fontSize: 14,
      color: '#059669',
      fontWeight: '700',
    },
    progressContainer: {
      paddingHorizontal: 20,
      marginBottom: 30,
    },
    progressTrack: {
      height: 6,
      backgroundColor: '#E5E7EB',
      borderRadius: 3,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#10B981',
      borderRadius: 3,
    },
    scrollView: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    welcomeSection: {
      alignItems: 'center',
      marginBottom: 40,
    },
    iconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
      borderWidth: 1,
      borderColor: 'rgba(16, 185, 129, 0.1)',
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: '#1F2937',
      textAlign: 'center',
      marginBottom: 10,
    },
    subtitle: {
      fontSize: 16,
      color: '#6B7280',
      textAlign: 'center',
      lineHeight: 24,
      paddingHorizontal: 10,
    },
    formSection: {
      gap: 25,
    },
    inputGroup: {
      gap: 8,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 5,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 40,
      paddingHorizontal: 15,
      paddingVertical: 10,
      gap: 12,
      borderWidth: 1.5,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    inputError: {
      borderColor: '#EF4444',
      backgroundColor: '#FEF2F2',
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: '#1F2937',
      fontWeight: '500',
    },
    errorText: {
      fontSize: 14,
      color: '#EF4444',
      marginTop: 5,
      fontWeight: '500',
    },
    helperText: {
      fontSize: 12,
      color: '#9CA3AF',
      marginTop: 5,
      lineHeight: 16,
    },
    testSection: {
      alignItems: 'center',
      gap: 10,
    },
    testButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      gap: 8,
      borderWidth: 1.5,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    testButtonLoading: {
      backgroundColor: '#F9FAFB',
      borderColor: '#D1D5DB',
    },
    testButtonDisabled: {
      backgroundColor: '#F9FAFB',
      borderColor: '#E5E7EB',
      opacity: 0.6,
    },
    testButtonText: {
      color: '#1F2937',
      fontSize: 16,
      fontWeight: '600',
    },
    testHelperText: {
      color: '#6B7280',
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    infoCards: {
      gap: 15,
    },
    infoCard: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      alignItems: 'center',
      gap: 15,
      borderWidth: 1,
      borderColor: '#F3F4F6',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    infoCardContent: {
      flex: 1,
    },
    infoCardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 4,
    },
    infoCardText: {
      fontSize: 14,
      color: '#6B7280',
      lineHeight: 20,
    },
    buttonContainer: {
      paddingHorizontal: 20,
      paddingBottom: 20,
      paddingTop: 10,
    },
    continueButton: {
      flexDirection: 'row',
      backgroundColor: '#10B981',
      paddingHorizontal: 40,
      paddingVertical: 18,
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 12,
    },
    buttonLoading: {
      backgroundColor: '#059669',
    },
    buttonDisabled: {
      backgroundColor: '#D1D5DB',
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    loadingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
  });