import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");
export const devicePairingStyles = StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    keyboardView: {
      flex: 1,
    },
    backgroundCircles: {
      position: 'absolute',
      width: '100%',
      height: '100%',
    },
    circle: {
      position: 'absolute',
      borderRadius: 1000,
    },
    circle1: {
      width: 250,
      height: 250,
      top: -125,
      right: -125,
      backgroundColor: 'rgba(16, 185, 129, 0.06)',
    },
    circle2: {
      width: 180,
      height: 180,
      bottom: -90,
      left: -90,
      backgroundColor: 'rgba(34, 197, 94, 0.05)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 20,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      flex: 1,
      textAlign: 'center',
    },
    stepIndicator: {
      fontSize: 14,
      color: '#059669',
      fontWeight: '700',
    },
    progressContainer: {
      paddingHorizontal: 20,
      marginBottom: 30,
    },
    progressTrack: {
      height: 6,
      backgroundColor: '#E5E7EB',
      borderRadius: 3,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#10B981',
      borderRadius: 3,
    },
    scrollView: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    welcomeSection: {
      alignItems: 'center',
      marginBottom: 40,
    },
    iconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
      borderWidth: 1,
      borderColor: 'rgba(16, 185, 129, 0.1)',
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: '#1F2937',
      textAlign: 'center',
      marginBottom: 10,
    },
    subtitle: {
      fontSize: 16,
      color: '#6B7280',
      textAlign: 'center',
      lineHeight: 24,
      paddingHorizontal: 10,
    },
    devicesSection: {
      gap: 25,
      marginBottom: 30,
    },
    roomSection: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    roomHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
    },
    roomInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    roomTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1F2937',
    },
    addDeviceButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F0FDF4',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      gap: 5,
    },
    addDeviceText: {
      color: '#10B981',
      fontSize: 14,
      fontWeight: '600',
    },
    devicesList: {
      gap: 10,
    },
    deviceItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#F9FAFB',
      borderRadius: 12,
      padding: 15,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    deviceInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 12,
    },
    deviceIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    deviceDetails: {
      flex: 1,
    },
    deviceName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#1F2937',
      marginBottom: 2,
    },
    deviceId: {
      fontSize: 12,
      color: '#6B7280',
      fontFamily: 'monospace',
    },
    deviceActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    statusIndicator: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    retryButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#FEF3C7',
      justifyContent: 'center',
      alignItems: 'center',
    },
    removeDeviceButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#FEE2E2',
      justifyContent: 'center',
      alignItems: 'center',
    },
    noDevicesContainer: {
      alignItems: 'center',
      paddingVertical: 20,
    },
    noDevicesText: {
      color: '#9CA3AF',
      fontSize: 14,
      fontStyle: 'italic',
    },
    summarySection: {
      backgroundColor: '#F0FDF4',
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: '#BBF7D0',
    },
    summaryTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#059669',
      marginBottom: 15,
      textAlign: 'center',
    },
    summaryStats: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    statItem: {
      alignItems: 'center',
    },
    statNumber: {
      fontSize: 24,
      fontWeight: '800',
      color: '#1F2937',
      marginBottom: 5,
    },
    statLabel: {
      fontSize: 12,
      color: '#6B7280',
      fontWeight: '600',    textTransform: 'uppercase',
  },
  buttonContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
    paddingTop: 15,
    backgroundColor: '#FFFFFF',
  },
  continueButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 16,
    borderRadius: 14,
    gap: 10,
    shadowColor: '#10B981',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  buttonLoading: {
    opacity: 0.8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  inputGroup: {
    marginBottom: 25,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4B5563',
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    gap: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#1F2937',
  },
  helperText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 8,
  },
  deviceTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  deviceTypeOption: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  deviceTypeOptionSelected: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
  },
  deviceTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 8,
  },
  deviceTypeTextSelected: {
    color: '#FFFFFF',
  },
  deviceIdContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  qrButton: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  modalActions: {
    flexDirection: 'row',
    padding: 20,
    gap: 15,
  },
  cancelButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
  },
  cancelButtonText: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '600',
  },
  addButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#10B981',
    borderRadius: 12,
    padding: 16,
  },
  addButtonDisabled: {
    opacity: 0.6,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  qrContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  qrHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  qrTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  qrCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  qrFrame: {
    width: width - 100,
    height: width - 100,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  qrCorner: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderLeftWidth: 4,
    borderTopWidth: 4,
    borderColor: '#10B981',
    top: 0,
    left: 0,
  },
  qrCornerTopRight: {
    right: 0,
    left: 'auto',
    borderRightWidth: 4,
    borderTopWidth: 4,
    borderLeftWidth: 0,
  },
  qrCornerBottomLeft: {
    top: 'auto',
    bottom: 0,
    borderLeftWidth: 4,
    borderBottomWidth: 4,
    borderTopWidth: 0,
  },
  qrCornerBottomRight: {
    top: 'auto',
    left: 'auto',
    right: 0,
    bottom: 0,
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderTopWidth: 0,
    borderLeftWidth: 0,
  },
  qrInstructions: {
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 30,
    textAlign: 'center',
  },
  qrScanButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 12,
  },
  qrScanButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  });