import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");
export const roomSetupStyles = StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    keyboardView: {
      flex: 1,
    },
    backgroundCircles: {
      position: 'absolute',
      width: '100%',
      height: '100%',
    },
    circle: {
      position: 'absolute',
      borderRadius: 1000,
    },
    circle1: {
      width: 250,
      height: 250,
      top: -125,
      right: -125,
      backgroundColor: 'rgba(16, 185, 129, 0.06)',
    },
    circle2: {
      width: 180,
      height: 180,
      bottom: -90,
      left: -90,
      backgroundColor: 'rgba(34, 197, 94, 0.05)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 20,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      flex: 1,
      textAlign: 'center',
    },
    stepIndicator: {
      fontSize: 14,
      color: '#059669',
      fontWeight: '700',
    },
    progressContainer: {
      paddingHorizontal: 20,
      marginBottom: 30,
    },
    progressTrack: {
      height: 6,
      backgroundColor: '#E5E7EB',
      borderRadius: 3,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#10B981',
      borderRadius: 3,
    },
    scrollView: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    welcomeSection: {
      alignItems: 'center',
      marginBottom: 40,
    },
    iconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
      shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
      borderWidth: 1,
      borderColor: 'rgba(16, 185, 129, 0.1)',
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: '#1F2937',
      textAlign: 'center',
      marginBottom: 10,
    },
    subtitle: {
      fontSize: 16,
      color: '#6B7280',
      textAlign: 'center',
      lineHeight: 24,
      paddingHorizontal: 10,
    },
    roomSection: {
      marginBottom: 30,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 20,
    },
    roomGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 15,
      marginBottom: 25,
    },
    roomItemWrapper: {
      position: 'relative',
    },
    roomItem: {
      width: (width - 70) / 2,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#F3F4F6',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    roomItemSelected: {
      borderColor: '#10B981',
      backgroundColor: '#F0FDF4',
    },
    roomIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#F9FAFB',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    roomIconContainerSelected: {
      backgroundColor: '#10B981',
    },
    roomName: {
      fontSize: 14,
      fontWeight: '600',
      color: '#1F2937',
      textAlign: 'center',
    },
    roomNameSelected: {
      color: '#059669',
    },
    checkMark: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#10B981',
      justifyContent: 'center',
      alignItems: 'center',
    },
    removeButton: {
      position: 'absolute',
      top: -8,
      right: -8,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#EF4444',
    },
    addRoomButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      borderWidth: 2,
      borderColor: '#10B981',
      borderStyle: 'dashed',
      gap: 10,
    },
    addRoomText: {
      color: '#10B981',
      fontSize: 16,
      fontWeight: '600',
    },
    addRoomForm: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    addRoomTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 15,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F9FAFB',
      borderRadius: 12,
      paddingHorizontal: 15,
      paddingVertical: 10,
      gap: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      marginBottom: 20,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: '#1F2937',
      fontWeight: '500',
    },
    iconSelectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 10,
    },
    iconGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 20,
    },
    iconOption: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#F9FAFB',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    iconOptionSelected: {
      backgroundColor: '#10B981',
      borderColor: '#10B981',
    },
    addRoomActions: {
      flexDirection: 'row',
      gap: 10,
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: '#F3F4F6',
      alignItems: 'center',
    },
    cancelButtonText: {
      color: '#6B7280',
      fontSize: 16,
      fontWeight: '600',
    },
    addButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: '#10B981',
      alignItems: 'center',
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    summarySection: {
      backgroundColor: '#F0FDF4',
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: '#BBF7D0',
    },
    summaryTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#059669',
      marginBottom: 15,
    },
    summaryList: {
      gap: 10,
    },
    summaryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    summaryItemText: {
      fontSize: 14,
      color: '#065F46',
      fontWeight: '600',
    },
    buttonContainer: {
      paddingHorizontal: 20,
      paddingBottom: 20,
      paddingTop: 10,
    },
    continueButton: {
      flexDirection: 'row',
      backgroundColor: '#10B981',
      paddingHorizontal: 40,
      paddingVertical: 18,
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      shadowColor: '#10B981',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 12,
    },
    buttonLoading: {
      backgroundColor: '#059669',
    },
    buttonDisabled: {
      backgroundColor: '#D1D5DB',
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    loadingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
  });